# Generated by Django 5.1.5 on 2025-02-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('idAnunciante', models.IntegerField()),
                ('idPet', models.IntegerField()),
                ('fotoDestaqueURL', models.URLField()),
                ('foto1', models.URLField()),
                ('foto2', models.URLField()),
                ('foto3', models.URLField()),
                ('foto4', models.URLField()),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idTipo', models.SmallIntegerField()),
                ('idRaca', models.SmallIntegerField()),
                ('peso', models.SmallIntegerField()),
                ('idade', models.SmallIntegerField()),
                ('idDono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=30)),
            ],
        ),
    ]
