# Generated by Django 5.1.5 on 2025-02-04 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0002_remove_anunciante_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='idAnunciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinder_pet.anunciante'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='idPet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinder_pet.pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='idDono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinder_pet.anunciante'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='idRaca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tinder_pet.raca'),
        ),
    ]
