# Generated by Django 5.1.5 on 2025-02-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0003_alter_anuncio_idanunciante_alter_anuncio_idpet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raca',
            old_name='raca',
            new_name='racas',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='idTipo',
        ),
        migrations.AddField(
            model_name='raca',
            name='tipo',
            field=models.SmallIntegerField(default=0),
        ),
    ]
