# Generated by Django 5.1.5 on 2025-02-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0006_anuncio_datapublicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.SmallIntegerField(null=True),
        ),
    ]
