# Generated by Django 5.1.5 on 2025-02-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0007_pet_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='tipo',
            field=models.SmallIntegerField(null=True),
        ),
    ]
