# Generated by Django 5.1.5 on 2025-02-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0008_anuncio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='titulo',
        ),
    ]
