# Generated by Django 5.1.5 on 2025-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0009_remove_anuncio_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciante',
            name='whatsapp',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
