# Generated by Django 5.1.5 on 2025-02-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0011_cidade_anunciante_idcidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='nome',
            new_name='cidades',
        ),
    ]
