# Generated by Django 5.1.5 on 2025-02-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0012_rename_nome_cidade_cidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciante',
            name='loginGoogle',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anunciante',
            name='senha',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
