# Generated by Django 5.1.5 on 2025-02-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0016_remove_anuncio_foto1_remove_anuncio_foto2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anunciante',
            old_name='idCidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='idAnunciante',
            new_name='anunciante',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='idPet',
            new_name='pet',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='idDono',
            new_name='dono',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='idRaca',
            new_name='raca',
        ),
    ]
