# Generated by Django 5.1.5 on 2025-02-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0017_rename_idcidade_anunciante_cidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='desc',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='titulo',
        ),
    ]
