# Generated by Django 5.1.5 on 2025-02-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0019_anunciante_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciante',
            name='querAdotar',
            field=models.BooleanField(default=False),
        ),
    ]
