# Generated by Django 5.1.5 on 2025-02-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0020_anunciante_queradotar'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciante',
            name='firstTime',
            field=models.BooleanField(default=True),
        ),
    ]
