# Generated by Django 5.1.5 on 2025-03-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0021_anunciante_firsttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciante',
            name='isONG',
            field=models.BooleanField(default=False),
        ),
    ]
