# Generated by Django 5.1.5 on 2025-03-10 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0022_anunciante_isong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField()),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinder_pet.anunciante')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinder_pet.anuncio')),
            ],
        ),
    ]
