# Generated by Django 5.1.5 on 2025-03-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0023_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='dataDoacao',
            field=models.DateField(null=True),
        ),
    ]
