# Generated by Django 5.1.5 on 2025-03-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0024_doacao_datadoacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciante',
            name='chavePIX',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anunciante',
            name='cnpj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='anunciante',
            name='endereço',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anunciante',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='anunciante',
            name='fotoCapa',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='anunciante',
            name='fotoPerfil',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='anunciante',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='anunciante',
            name='site',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='anunciante',
            name='sobre',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='anunciante',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
