# Generated by Django 5.1.5 on 2025-03-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0025_anunciante_chavepix_anunciante_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciante',
            name='nomeONG',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
