# Generated by Django 5.1.5 on 2025-04-03 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0028_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField(null=True)),
                ('aberta', models.BooleanField(default=False)),
                ('anuncio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tinder_pet.anuncio')),
                ('doacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tinder_pet.doacao')),
            ],
        ),
    ]
