# Generated by Django 5.1.5 on 2025-04-03 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0029_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tinder_pet.anunciante'),
        ),
    ]
