# Generated by Django 5.1.5 on 2025-04-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0030_notificacao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='dataNotificacao',
            field=models.DateField(null=True),
        ),
    ]
