# Generated by Django 5.1.5 on 2025-04-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0031_notificacao_datanotificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='dataNotificacao',
            field=models.DateTimeField(null=True),
        ),
    ]
