# Generated by Django 5.1.5 on 2025-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0032_alter_notificacao_datanotificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
    ]
