# Generated by Django 5.1.5 on 2025-04-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0034_alter_pet_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tinder_pet.raca'),
        ),
    ]
