# Generated by Django 5.1.5 on 2025-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder_pet', '0036_rename_queradotar_anunciante_emailconfirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciante',
            name='token',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
